version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./site:/usr/share/nginx/html
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf      
    networks:
      - docker-network

  php:
    image: php:fpm
    container_name: php
    volumes:
      - ./site:/usr/share/nginx/html
    networks:
      - docker-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: foot79
      MYSQL_DATABASE: account_prod
      MYSQL_USER: foonghk
      MYSQL_PASSWORD: foot79
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - docker-network  
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 82:80  
    networks:
      - docker-network   

volumes:
  dbdata:

networks:
  docker-network:
    driver: bridge
